apiVersion: apps/v1
metadata:
  name: pareto-devops
spec:
  replicas: 1
    spec:
      containers:
      - name: pareto-devops
        image: 123456789.dkr.ecr.us-west-1.amazonaws.com/pareto-devops:production-latest
        ports:
          - containerPort: 8080
        env:
          - name: MYSQL_URI
            valueFrom:
              secretKeyRef:
                name: pareto-secret
                key: MYSQL_URI
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.05"
